" Vundle configfile source. Add the bundles to ~/.vundle and not here
" Do not add any config BEFORE this line
source ~/.vundle
source ~/.vim_functions

" BASIC CONFIG {{{1

syn on
set bg=dark
set is ic hls scs aw ru si ai
set sw=4 sts=4 ts=4
set et!
set wildmenu wim=longest,list
set cursorline relativenumber
set nocompatible modeline modelines=1
set showmode showcmd ttyfast
set laststatus=2
set scrolloff=3
set undofile

colorscheme molokai

" Setting swap and undo directories
set undodir=$HOME/.vim/undo
set backupdir=$HOME/.vim/swap
set directory=$HOME/.vim/swap

" Reload config file
map <F1> :source ~/.vimrc<CR>

" Color fix
let &t_Co=256

" REMAPS {{{1

cab W w
cab Wq wq

" Fix j/k
" nnoremap j gj
" nnoremap k gk

" Easily return to normal mode using jj or kk
inoremap jj <ESC>

" Easily clean search hilighting with \<space>
nnoremap <leader><space> :noh<cr>

" Easily clean search hilighting with \<space>
nnoremap <leader>n :set relativenumber!<cr>

" Easily set paste!
nnoremap <leader>p :set paste!<cr>

" Remove trailing whitespace with \q
nnoremap <leader>q :%s/\s\+$//<cr>:let @/=''<CR>

" Easy switch wrap/nowrap
nnoremap <leader>w :set wrap!<CR>

" Runs bash
nnoremap <leader>b :!bash<CR>

" Easy open/close folds
nnoremap <Space> za
vnoremap <Space> za
nnoremap <S-Space> zA
vnoremap <S-Space> zA

" Remaps to easily switch to other split:
" nnoremap <D-h> <C-w>h
" nnoremap <D-j> <C-w>j
" nnoremap <D-k> <C-w>k
" nnoremap <D-l> <C-w>l

" Requires tpope/vim-uninpaired
" Bubble single lines
nmap <C-k> [e
nmap <C-j> ]e
" Bubble multiple lines
vmap <C-k> [egv
vmap <C-j> ]egv

" MAPPING MAGIC {{{1

" Toggle visible whitespace
nmap <leader>l :set list!<CR>
set listchars=tab:▸\ ,eol:¬

" Open VSplit with vimrc
nnoremap <leader>ev <C-w><C-v><C-l>:e $MYVIMRC<cr>

" Open VSplit e move to it
nnoremap <leader>v <C-w>v<C-w>l

" Open file Browser vertically
nnoremap <leader>\| :Ve<cr>

" Open file Browser horizontally
nnoremap <leader>_ :Se<cr>

" BUNDLES CONFIG {{{1

" NERDTree Toggle
map <leader>t :NERDTreeToggle<CR>
let NERDTreeHijackNetrw=0

" NERDTree auto close
au bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Gundo Toggle
nnoremap <leader>u :GundoToggle<CR>

" Gundo Settings
let g:gundo_right = 1
let g:gundo_close_on_revert = 1
let g:gundo_preview_bottom = 1

" Taglist plugin mapping
nmap <leader>o :TagbarToggle<CR>

" Taglist config
"let g:tagbar_autofocus = 1
"let g:tagbar_autoclose = 1
let g:tagbar_compact = 1
let g:tagbar_autoshowtag = 1

" Powerline Fancy Settings
let g:Powerline_symbols = 'fancy'

" ADVANCED CONFIGS {{{1

" Omnicomplete
set ofu=syntaxcomplete#Complete
autocmd FileType python     set omnifunc=pythoncomplete#Complete

" Return cursor to where left
au BufWinLeave ?* mkview
au BufWinEnter ?* silent loadview

" Save when losing focus
au FocusLost ?* :wa

" Custom file syntax
au BufRead,BufNewFile *.pp set filetype=puppet
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} set ft=markdown

" IDE style 'run' commands {{{2
" Bash
au FileType sh map <F11> :w<CR>:!clear && bash "%"<CR>
au FileType sh map <F12> :w<CR>:!clear && bash -x "%"<CR>

" Python
au FileType python map <F11> :w<CR>:!clear && python "%"<CR>

" MarkDown
au FileType markdown map <F11> :w<CR>:!open -a /Applications/Google\ Chrome.app "%"<CR>

" Folding Configs {{{2

au BufRead,BufNewFile ?* set foldtext=FoldText()

" SSHconfig
au BufRead,BufNewFile *.ssh/config set foldexpr=SSHconfigFolds()

" Vim configs
au FileType vim set foldmethod=marker

" MACVIM CONFIG {{{1

if has("gui_running")
	colorscheme molokai
	set guioptions-=r
	set guioptions-=L
	set guifont=Menlo:h12

	" IDE style 'run' commands
    " Bash
    au BufNewFile,BufRead *.sh map <F11> :w<CR>:!bash "%"<CR>
    au BufNewFile,BufRead *.sh map <F12> :w<CR>:!bash -x "%"<CR>

    " Python
    au BufNewFile,BufRead *.py map <F11> :w<CR>:!python "%"<CR>
endif

