# Sources
source ~/.ventures
source ~/.aws-credentials
source ~/.bash_functions

# Environment variables
export BROWSER="less"
export PAGER="less"
export EDITOR="vim"
export CLICOLOR=1
export LC_ALL="en_US.UTF-8"
export GOPATH="/opt/go"

# Set Colors shortcuts
export CBOLD="\[$(tput bold)\]" 
export CRED="\[$(tput setaf 1)\]"
export CGREEN="\[$(tput setaf 2)\]"
export CYELLOW="\[$(tput setaf 3)\]"
export CBLUE="\[$(tput setaf 4)\]"
export CMAGENTA="\[$(tput setaf 5)\]"
export CCYAN="\[$(tput setaf 6)\]"
export CWHITE="\[$(tput setaf 7)\]"
export CRESET="\[$(tput sgr0)\]"

export PS1="$CCYAN\u$CWHITE@$CGREEN\h$CWHITE:$CYELLOW\w\n\`[[ \$? = 0 ]] && echo \[\e[34m\] || echo \[\e[31m\]\`> $CRESET"

# Keep History under control
# export PROMPT_COMMAND="history -a; history -n"
export HISTCONTROL=erasedups
export HISTSIZE=100000
shopt -s histappend
shopt -s cdspell

# Bash Aliases
alias ls="ls -FG"
alias df="df -kh"
alias du="du -kc"
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias fgrep="fgrep --color=always"
alias sgrep="grep -sIl"
alias vi="mvim"
alias vim="mvim"
alias vimdiff="mvim -d"

# Vundle Aliases
alias vundleinstall="vim +PluginInstall +qall"
alias vundleclean="vim +PluginClean! +qall"
alias vundlelist="vim +PluginList +qall"
alias vundleupdate="vim +PluginUpdate +qall"

# Fix wrong ctags version
alias ctags="/usr/local/bin/ctags"

# Other Helper Aliases
alias md5sum="openssl dgst -md5"
alias awskeys="cd /opt/git/rocket/infra/private/aws/keys"
alias vimrc="mvim ~/.vimrc"
alias gitlog="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias fixow='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'
alias sshconfig="mvim ~/.ssh/config"
alias bashprofilesource="source ~/.bash_profile"
alias updatedb="sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist"
alias taskf="vim /Users/metalrufflez/Dropbox/Docs/tasks/fetchplus.task"
alias taskr="vim /Users/metalrufflez/Dropbox/Docs/tasks/rocket.task"
alias taskp="vim /Users/metalrufflez/Dropbox/Docs/tasks/personal.task"

# SSH Aliases auto-complete
complete -o default -W "$(grep -i "^host" $HOME/.ssh/config | cut -d" " -f2-)" scp sftp ssh
complete -C aws_completer aws

# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\E[5;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[1;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[m'           # end mode
export LESS_TERMCAP_so=$'\E[1;33;41m'    # begin standout-mode - info box
export LESS_TERMCAP_se=$'\E[m'           # end standout-mode
export LESS_TERMCAP_us=$'\E[4;36m'       # begin underline
export LESS_TERMCAP_ue=$'\E[m'           # end underline
