# Sources
source ~/.ventures
source ~/.aws-credentials

# Environment variables
export BROWSER="less"
export PAGER="less"
export EDITOR="vim"
export CLICOLOR=1
export LC_ALL="en_US.UTF-8"

# Set Colors shortcuts
export CBOLD="\[$(tput bold)\]" 
export CBLUE="\[$(tput setaf 4)\]"
export CWHITE="\[$(tput setaf 7)\]"
export CGREEN="\[$(tput setaf 2)\]"
export CYELLOW="\[$(tput setaf 3)\]"
export CRED="\[$(tput setaf 1)\]"
export CRESET="\[$(tput sgr0)\]"

export PS1="$CBLUE\u$CWHITE@$CGREEN\h$CWHITE|\$(count_todo)$CWHITE:$CRED\w\n$CWHITE\\$ $CRESET"
#export PS1="$CBLUE\u$CWHITE@$CGREEN\h$CWHITE:$CRED\w\n$CWHITE\\$ $CRESET"

# Keep History under control
export HISTCONTROL=erasedups
export HISTSIZE=100000
shopt -s histappend
shopt -s cdspell

# ec2-api-tools config
export JAVA_HOME="$(/usr/libexec/java_home)"
export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.6.12.0/libexec"
export AWS_RDS_HOME="/usr/local/Cellar/rds-command-line-tools/1.14.001/libexec"
export AWS_ELASTICACHE_HOME="/usr/local/Cellar/aws-elasticache/1.9.000/libexec"

# Bash Aliases
alias ls="ls -FG"
alias df="df -kh"
alias du="du -kc"
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias fgrep="fgrep --color=always"
alias sgrep="grep -sIl"
alias vi="mvim"

# Vundle Aliases
alias vundleinstall="vim +BundleInstall +qall"
alias vundleclean="vim +BundleClean! +qall"

# Fix wrong ctags version
alias ctags="/usr/local/bin/ctags"

# Other Helper Aliases
alias md5sum="openssl dgst -md5"
alias awskeys="cd /opt/git/infra/private/aws/keys"
alias vimrc="mvim ~/.vimrc"
alias gitlog="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias fixow='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'
alias sshconfig="mvim ~/.ssh/config"
alias bashprofilesource="source ~/.bash_profile"

# t alias
#alias t='python /Users/metalrufflez/Dropbox/Apps/t/t.py --task-dir /Users/metalrufflez/Dropbox/Sync/tasks --list work'
#alias c='python /Users/metalrufflez/Dropbox/Apps/t/t.py --task-dir /Users/metalrufflez/Dropbox/Sync/tasks --list personal'
alias t="$HOME/Dropbox/Apps/todo.txt/todo.sh -c"
alias c="$HOME/Dropbox/Apps/todo.txt/todo.sh -c ls +caio"
alias w="$HOME/Dropbox/Apps/todo.txt/todo.sh -c ls -+caio"
alias d="$HOME/Dropbox/Apps/todo.txt/todo.sh -c do"
alias p="$HOME/Dropbox/Apps/todo.txt/todo.sh -c pri"

# SSH Aliases auto-complete
complete -o default -W "$(grep -i "^host" $HOME/.ssh/config | cut -d" " -f2-)" scp sftp ssh

# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\E[5;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[1;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[m'           # end mode
export LESS_TERMCAP_so=$'\E[1;33;41m'    # begin standout-mode - info box
export LESS_TERMCAP_se=$'\E[m'           # end standout-mode
export LESS_TERMCAP_us=$'\E[4;36m'       # begin underline
export LESS_TERMCAP_ue=$'\E[m'           # end underline

# Sprunge function, use it after a |
function sprunge() {
    lang=${1:+?$1}
    url=$(curl --silent -F 'sprunge=<-' http://sprunge.us)
    echo -n "${url# }$lang" | pbcopy
}

# Latex compiler helper
function latexpress() {
    output_dir="/tmp/latex_out"
    filename=$(echo $* | egrep --color="never" -o "\w+.tex" | cut -d. -f1)

    mkdir -p $output_dir
    xelatex -halt-on-error -output-directory=$output_dir $* || return
    mv $output_dir/${filename}.pdf .
    open ${filename}.pdf
}

function ca() {
    t a "+caio - $*"
}
